#!/bin/bash

set -ex

# TODO differentiate two github icons
jupyter serverextension disable --py jupyter_offlinenotebook --sys-prefix
jupyter nbextension disable --py jupyter_offlinenotebook --sys-prefix

# TODO build args seem to be necessary in low memory environment
jupyter lab build --dev-build=False --minimize=False

# note - only does anything if explicitly opted in
mkdir -p "$(jupyter --config-dir)"  # ugh
cat <<EOF >>"$(jupyter --config-dir)/jupyter_notebook_config.py"
c.BalletApp.tel = True
c.BalletApp.telserver = 'https://sleepy-ravine-08709.herokuapp.com/api/v1'
EOF

ipython profile create
cat <<EOF >> $(ipython profile locate)/startup/01-patch.py
import ballet_tel
ballet_tel.install()
EOF
